### ISSUE TITLE
Compilation error when trying to install "npm install @industrialshields/rpiplc" and rpiplc-lib library is not installed

### ISSUE THREAD

**Issue by anis-bougrine** [Industrial-Shields/node-librpiplc#1]
The command "npm install @industrialshields/rpiplc" generates the next compilation error:
`../src/fn.h:6:10: fatal error: rpiplc.h: No such file or directory
 #include <rpiplc.h>
          ^~~~~~~~~~
compilation terminated.                                                                                                                                                               `

I realized that I have to install "rpiplc-lib" manually from this [repository](https://github.com/Industrial-Shields/rpiplc-lib).
This have to me automatized in the binding.gyp script.

**Comment by JoanVC100** [comment]
Hi Anis,

I'm afraid I can't accept your pull request. This library (and node-red-librpiplc) should be used with our Raspberry PLCs, which come with our own images and the library pre-installed.

We also have installation scripts that make all the changes necessary to convert a Raspberry image to one that is pretty much the same as the pre-installed one. And among other changes, this script also installs the librpiplc C library. You can check the different scripts in [https://apps.industrialshields.com/main/rpi/](https://apps.industrialshields.com/main/rpi/)

I am closing this issue as solved.
